# Generated by Django 5.2.5 on 2025-09-02 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recipe_likes_alter_like_recipe_alter_like_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Healthy Salads', 'Healthy Salads'), ('Desserts & Sweets', 'Desserts & Sweets'), ('Quick Snacks', 'Quick Snacks'), ('Drinks & Beverages', 'Drinks & Beverages'), ('Non-Vegetarian', 'Non-Vegetarian'), ('Vegetarian & Vegan', 'Vegetarian & Vegan')], max_length=50),
        ),
    ]
